#!/usr/bin/env ruby

def github_auto
    branch = `git rev-parse --abbrev-ref HEAD`
    commit_answer = ''
    print "Commit Message? "
    commit_answer = gets.chomp
    `git add .`
    `git commit -m "#{commit_answer}"`
    `git push origin #{branch}`
    puts "-" * 20
    puts "Pushed changes to #{branch}"
    puts "-" * 20
end

github_auto

# hello from ubuntu