# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rails secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

# Shared secrets are available across all environments.

# shared:
#   api_key: a1B2c3D4e5F6

# Environmental secrets are only available for that specific environment.

development:
  secret_key_base: e1ab095cfc02160a97f1445aceb70ac0b480f8810e26feef9808cbd9406a6f823adbfb09bb56379962c8601ee66644dd21caa59db04f4e1141e740068d19e861

test:
  secret_key_base: 0a807c85331b98d1f2f3a742d1317d17d37e615f76b3dfc9d646136919ab05c42397d869d0f13242c5bdeacbb02a9b0a82a08fb9796547f107e570fb8af295e6

# Do not keep production secrets in the unencrypted secrets file.
# Instead, either read values from the environment.
# Or, use `bin/rails secrets:setup` to configure encrypted secrets
# and move the `production:` environment over there.

production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
